id: ENDLESS_DIMENSION_TEMPLATE
version: 1.0.0
author: "Endless Dimensions"

generator: NOISE_3D
vanilla: minecraft:overworld
vanilla-generation: minecraft:overworld

addons:
  biome-provider-single: "1.+"
  biome-provider-pipeline: "2.+"
  biome-provider-extrusion: "1.+"
  chunk-generator-noise-3d: "1.+"
  config-biome: "1.+"
  config-flora: "1.+"
  config-noise-function: "1.+"
  config-ore: "1.+"
  config-palette: "1.+"
  config-distributors: "1.+"
  config-locators: "1.+"
  config-feature: "1.+"
  structure-terrascript-loader: "1.+"
  structure-sponge-loader: "1.+"
  language-yaml: "1.+"
  generation-stage-feature: "1.+"
  structure-function-check-noise-3d: "1.+"
  palette-block-shortcut: "1.+"
  structure-block-shortcut: "1.+"
  terrascript-function-sampler: "1.+"
  locator-slant-noise-3d: "1.+"

# Default shell (overworld_open). PackFactory will swap this for other shells.
biomes: $shells/overworld_open/biomes.yml:biomes

stages:
  - id: global-preprocessors
    type: FEATURE
  - id: preprocessors
    type: FEATURE
  - id: structures
    type: FEATURE
  - id: landforms
    type: FEATURE
  - id: slabs
    type: FEATURE
  - id: ores
    type: FEATURE
  - id: deposits
    type: FEATURE
  - id: river-decoration
    type: FEATURE
  - id: trees
    type: FEATURE
  - id: processors
    type: FEATURE
  - id: underwater-flora
    type: FEATURE
  - id: flora
    type: FEATURE
  - id: postprocessors
    type: FEATURE

slant:
  calculation-method: DotProduct
