stages:
  - type: REPLACE_LIST
    sampler:
      type: CELLULAR
      return: CellValue
      frequency: 1 / 500 / ${customization.yml:outer-end-biome-scale}
    default-from: ring1
    default-to:
      - END_HIGHLANDS: 1
      - HANGING_ISLES: 1
      - SHATTERED_END: 1
      - SHATTERED_FOREST: 1
    to:
      ring2:
        - TAINTED_END: 1
        - DARK_END: 1
        - AMETHYST_END: 1
        - CHORAL_DEADLANDS: 1
      ring3:
        - IVORY_EMPYREAN: 1
        - VERMILION_WILDS: 1
        - CRIM_THICKET: 1
        - STYGIAN_BARRENS: 1
      ring4:
        - MAUVE_JUNGLE: 1
        - END_WILDS: 1
        - CHORUVE_WOODS: 1
        - TWISTED_GROVE: 1

  - type: REPLACE
    sampler:
      type: CELLULAR
      return: CellValue
      frequency: 1 / 600 / ${customization.yml:outer-end-biome-scale}
    from: ring5
    to:
      - END_HIGHLANDS: 1
      - HANGING_ISLES: 1
      - SHATTERED_END: 1
      - SHATTERED_FOREST: 1

      - TAINTED_END: 1
      - DARK_END: 1
      - AMETHYST_END: 1
      - CHORAL_DEADLANDS: 1

      - IVORY_EMPYREAN: 1
      - VERMILION_WILDS: 1
      - CRIM_THICKET: 1
      - STYGIAN_BARRENS: 1

      - MAUVE_JUNGLE: 1
      - END_WILDS: 1
      - CHORUVE_WOODS: 1
      - TWISTED_GROVE: 1
      - ROSETTE_POOLS: 1