id: REIMAGEND
version: 3.0.0
author: "Aureus, RogueShade"

generator: NOISE_3D

vanilla: "minecraft:the_end"
vanilla-generation: "minecraft:end"

addons:
  biome-provider-pipeline: "2.+"
  biome-provider-single: "1.+"
  biome-provider-image: "1.+"
  biome-provider-extrusion: "1.+"
  chunk-generator-noise-3d: "1.+"
  config-biome: "1.+"
  config-flora: "1.+"
  config-noise-function: "1.+"
  config-ore: "1.+"
  config-palette: "1.+"
  config-distributors: "1.+"
  config-locators: "1.+"
  config-feature: "1.+"
  structure-terrascript-loader: "1.+"
  structure-sponge-loader: "1.+"
  language-yaml: "1.+"
  generation-stage-feature: "1.+"
  structure-function-check-noise-3d: "1.+"
  palette-block-shortcut: "1.+"
  structure-block-shortcut: "1.+"
  terrascript-function-sampler: "1.+"

# ---
# Biome distribution
# ---
# Several preset biome providers are available to choose from below.

# To pick a different preset you can uncomment the line starting with 'biomes:'
# under the preset name, and comment the old preset that was previously set.
# (Not commenting the old one will result in an error!)

# Default biome distribution
biomes: $biome-distribution/presets/default.yml:biomes

# Aether world biome distribution
#biomes: $biome-distribution/presets/aether.yml:biomes

# Single biome - Generates a single biome, as well as void pockets.
#biomes: $biome-distribution/presets/single.yml:biomes
preset-single-biome: END_HIGHLANDS

# Single debug biome - Used for debugging a singular biome, should not be used for regular world generation
#biomes: $biome-distribution/presets/single_debug.yml:biomes
preset-single-debug-biome: END_HIGHLANDS

# Regular biome distribution
#biomes: $biome-distribution/presets/alternative/normal.yml:biomes

# Vanilla-Like biome distribution
#biomes: $biome-distribution/presets/alternative/vanilla-ish.yml:biomes

# Vanilla-Like-Enhanced biome distribution
#biomes: $biome-distribution/presets/alternative/vanilla-ish_enhanced.yml:biomes

# BetterEnd biome distribution (Dfsek's BetterEnd Plugin)
#biomes: $biome-distribution/presets/alternative/betterend.yml:biomes

# Normal 3D biome distribution
#biomes: $biome-distribution/presets/alternative/normal_3d.yml:biomes

stages:
  # NOTE - This key must only be defined in biomes/abstract/base.yml
  - id: global-preprocessors
    type: FEATURE
  
  # Misc features that are treated as small modifications to the initial chunk generation.
  - id: preprocessors
    type: FEATURE
  
  - id: buildings
    type: FEATURE

  # Used for things like boulders and features that act like a part of the terrain.
  - id: landforms
    type: FEATURE
  
  # Adds slab versions of some blocks to make terrain look smoother.
  - id: slabs
    type: FEATURE
  
  # Self-explanatory - used to generate ores.
  # NOTE - Individual biomes should extend from configs in biomes/abstract/features/ores
  #        rather than overwriting this key themselves.
  - id: ores
    type: FEATURE
  
  # Adds things like dirt, andesite and gravel patches.
  # NOTE - Individual biomes should extend from configs in biomes/abstract/features/deposits
  #        rather than overwriting this key themselves.
  - id: deposits
    type: FEATURE
  
  # Used for larger things that generate on the surface like trees, some other features are
  # also treated as trees like ice spikes.
  - id: trees
    type: FEATURE
    
  # Used for small features placed on the surface like tall grass and vines.
  - id: flora
    type: FEATURE
  
  # Used to generate features that must come after all other features, such as snow on trees.
  - id: postprocessors
    type: FEATURE

functions:
  "<<":
    - math/functions/terrace.yml:functions
    - math/functions/lerp.yml:functions
    - math/functions/maskSmooth.yml:functions

samplers:
  "<<":
    - math/samplers/simplex.yml:samplers
    - math/samplers/spots.yml:samplers

blend:
  palette:
    resolution: 2
    amplitude: 2
    sampler:
      type: WHITE_NOISE

slant:
  calculation-method: DotProduct
