# Shell metadata for end-like geometry.
top-y: 255
ocean-level: 0
cloud-y: 128
deepslate-top: 0
bedrock-top: 0
bottom-y: 0

palette-slant-generic:
  - BLOCK:minecraft:end_stone: $meta.yml:top-y

palette-underwater:
  - BLOCK:minecraft:end_stone: ${meta.yml:ocean-level} - 1

palette-bottom:
  - BLOCK:minecraft:end_stone: $meta.yml:top-y
  - BLOCK:minecraft:bedrock: $meta.yml:bedrock-top
  - BLOCK:minecraft:bedrock: $meta.yml:bottom-y
