# Shell metadata for nether-like geometry.
top-y: 255
ocean-level: 32
cloud-y: 128
deepslate-top: 7
bedrock-top: 5
bottom-y: 0

palette-slant-generic:
  - BLOCK:minecraft:netherrack: $meta.yml:top-y

palette-underwater:
  - BLOCK:minecraft:lava: ${meta.yml:ocean-level} - 1

palette-bottom:
  - BLOCK:minecraft:netherrack: $meta.yml:top-y
  - BLOCK:minecraft:bedrock: $meta.yml:bedrock-top
  - BLOCK:minecraft:bedrock: $meta.yml:bottom-y
